image: Visual Studio 2019
configuration: Release
build:
  verbosity: minimal

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

skip_branch_with_pr: true

install:
  - ps: dotnet tool install -g Codecov.Tool
  - ps: dotnet tool install -g GitVersion.Tool --version 5.1.3

before_build:
  - ps: dotnet gitversion /l console /output buildserver

build_script:
  - ps: .\build.ps1

artifacts:
  - path: 'artifacts\*.nupkg'
    name: NuGet Packages

deploy:
  - provider: NuGet
    api_key:
      secure: oy2gumcvgjc4hsq6xhuq3n5mntn5qo4uxazsfwq56gp56y
