image: Visual Studio 2019
configuration: Release
build:
  verbosity: minimal

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

skip_branch_with_pr: true

build_script:
  - ps: .\build.ps1

artifacts:
  - path: 'artifacts\*.nupkg'
    name: NuGet Packages

deploy:
  - provider: NuGet
    api_key:
      secure: hzqXBR29mxy+SLV54qaNEUdEiO6pHNkbrXMVl7qvREgqjg2D50PiwH3sn54CpLcu
