image: Visual Studio 2019
configuration: Release
build:
  verbosity: minimal

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

skip_branch_with_pr: true

build_script:
  - ps: .\build.ps1

deploy:
  - provider: NuGet
    api_key:
      secure: 43D5nRU0LMORcn3Gol4JExIezvoHOBqejFhtYg6BEA5Nn1xWGJo1AVj5NeaKvh/N
    artifact: artifacts/*.nupkg
