version: 1
update_configs:
  - package_manager: dotnet:nuget
    directory: Source/GreetingTasks
    update_schedule: live
    default_labels:
      - dependencies
    allowed_updates:
      - match:
          update_type: all
          dependency_type: direct
